### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by pradipcyb** [kingfisherphuoc/EasyFilePickerDialog#3]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
 	at easyfilepickerdialog.kingfisher.com.library.view.FilePickerDialogFragment.onItemClick(FilePickerDialogFragment.java:146)
 	at easyfilepickerdialog.kingfisher.com.library.adapter.BaseViewHolder.onClick(BaseViewHolder.java:27)
 	at android.view.View.performClick(View.java:5201)
 	at android.view.View$PerformClick.run(View.java:21163)
 	at android.os.Handler.handleCallback(Handler.java:746)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5443)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by kingfisherphuoc** [comment]
@pradipcyb nice catch, guy. It will be resolved in the next release.

**Comment by pradipcyb** [comment]
Thanks
